### ISSUE TITLE
Remark 2.26

### ISSUE THREAD

**Issue by ludkinm** [optimaltransport/optimaltransport.github.io#3]
Is remark 2.26 in arxiv version v3 of the book correct?
Counter-example:
a = (2/3, 1/3); 
b = (1/3, 2/3); 
norm(a-b) = 2/3
but an optimal P = [[1,1],[0,1]] with L_C(a,b) = 1/3 

(I thought maybe this is meant to be an inequality like remark 8.2 but for probability vectors)

Is your definition of 1-norm the L1-norm, or is it something else? 
Or am I completely wrong somewhere!?

**Comment by fkastner** [comment]
I think they forgot a factor of 1/2 to account for the fact that you're counting every mass that has to be moved twice (once where it comes from and once where it goes to).
So `L_C(a,b) = 1/2*||a-b||_1`.

**Comment by ludkinm** [comment]
@fkastner thanks, that does look like the case!
